---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ name }}-charm
  name: {{ name }}-charm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ name }}-charm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ name }}-charm
    spec:
      serviceAccountName: {{ name }}-charm
      containers:
      - image: {{ image }}
        name: dex
        command: ["dex", "serve", "/etc/dex/cfg/config.yaml"]
        ports:
        {% if tls_secret %}
        - name: https
        {% else %}
        - name: http
        {% endif %}
          containerPort: {{ target_port }}
        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
        {% if tls_secret %}
        - name: certs
          mountPath: /certs
          readOnly: true
        {% endif %}
        env:
          - name: KUBERNETES_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CONFIG_HASH
            value: {{ config_hash }}
      volumes:
      - name: config
        configMap:
          name: {{ name }}-charm
          items:
          - key: config.yaml
            path: config.yaml
      {% if tls_secret %}
      - name: certs
        secret:
          defaultMode: 420
          secretName: {{ tls_secret }}
      {% endif %}
