---
apiVersion: v1
kind: Service
metadata:
  name: {{ name }}-charm
spec:
  type: {{ service_type }}
  ports:
  - name: {{ name }}
    port: {{ port }}
    protocol: TCP
    targetPort: {{ port }}
    {% if service_type == "NodePort" %}
    nodePort: {{ service_port }}
    {% endif %}
  selector:
    app.kubernetes.io/name: {{ name }}-charm

