---
apiVersion: v1
kind: Service
metadata:
  name: {{ name }}-charm
spec:
  type: {{ service_type }}
  ports:
  {% if tls_secret %}
  - name: https
  {% else %}
  - name: http
  {% endif %}
    port: {{ port }}
    protocol: TCP
    targetPort: {{ target_port }}
    {% if service_type == "NodePort" %}
    nodePort: {{ service_port }}
    {% endif %}
  selector:
    app.kubernetes.io/name: {{ name }}-charm

